data_path: ./data/dataset_all_center.yaml
conf_file: ./configs/yolov6s.py
img_size: 640
batch_size: 64
epochs: 200
workers: 8
device: '5'
eval_interval: 20
eval_final_only: false
heavy_eval_range: 50
check_images: false
check_labels: false
output_dir: ./runs/train
name: positive_negative
dist_url: env://
gpu_count: 0
local_rank: -1
resume: false
rank: -1
world_size: 1
save_dir: ./runs/train/positive_negative
